services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rewardtracking
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/rewardtracking?schema=public"
      NEXTAUTH_URL: "http://localhost:3000"
      WATCHPACK_POLLING: "true"
      NODE_ENV: "development"
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: npm run dev

volumes:
  db_data:
